# Generated by Django 6.1 on 2026-08-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_cliente_alter_producto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='productos/'),
        ),
    ]
