# Generated by Django 6.1 on 2026-08-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=15, help_text='Tarifa general en Ecuador: 15% (productos de primera necesidad: 0%).', max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'configuracion',
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
