# Generated by Django 6.1 on 2026-08-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_configuracion_venta_iva_venta_iva_porcentaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='banco',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='venta',
            name='comprobante',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('mixto', 'Mixto')], default='efectivo', max_length=15),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_transferencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
