# Generated by Django 6.1 on 2026-08-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_sucursal_movimientokardex'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='correo',
            field=models.EmailField(blank=True, default='', help_text='Correo electrónico de contacto.', max_length=254),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='direccion',
            field=models.CharField(blank=True, default='', help_text='Dirección de la matriz o del establecimiento.', max_length=250),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='establecimiento',
            field=models.CharField(blank=True, default='001', help_text='Código del establecimiento (3 dígitos, ej. 001).', max_length=3),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='lema',
            field=models.CharField(blank=True, default='', help_text='Lema o texto libre que se imprime bajo el nombre (opcional).', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='nombre_empresa',
            field=models.CharField(blank=True, default='JAGUAR', help_text='Razón social o nombre comercial que aparece en la factura.', max_length=150),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='punto_emision',
            field=models.CharField(blank=True, default='001', help_text='Código del punto de emisión (3 dígitos, ej. 001).', max_length=3),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='ruc',
            field=models.CharField(blank=True, default='', help_text='Número de RUC del emisor (13 dígitos).', max_length=13),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='telefono',
            field=models.CharField(blank=True, default='', help_text='Teléfono de contacto.', max_length=30),
        ),
    ]
