# Generated by Django 6.1 on 2026-08-28 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_configuracion_correo_configuracion_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_100', models.PositiveIntegerField(default=0)),
                ('b_50', models.PositiveIntegerField(default=0)),
                ('b_20', models.PositiveIntegerField(default=0)),
                ('b_10', models.PositiveIntegerField(default=0)),
                ('b_5', models.PositiveIntegerField(default=0)),
                ('b_1', models.PositiveIntegerField(default=0)),
                ('m_1', models.PositiveIntegerField(default=0)),
                ('m_050', models.PositiveIntegerField(default=0)),
                ('m_025', models.PositiveIntegerField(default=0)),
                ('m_010', models.PositiveIntegerField(default=0)),
                ('m_005', models.PositiveIntegerField(default=0)),
                ('m_001', models.PositiveIntegerField(default=0)),
                ('caja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conteo', to='principal.caja')),
            ],
        ),
    ]
